=== tuscanmoon/XML-Course-Work-2/examiners.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://webspace.stu.qmul.ac.uk/~ac08162/amcm043/coursework2/examiner"
  xmlns:exm="http://webspace.stu.qmul.ac.uk/~ac08162/amcm043/coursework2/examiner"
  elementFormDefault="qualified">

  <!-- Main subject declaration -->
  <xs:element name="examinerCV">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="examiner" type="exm:examiner" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!-- Simple Type Declarations -->
  <xs:simpleType name="firstName">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="identificationNumber">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="identificationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Driver Number"/>
      <xs:enumeration value="National Indentity Number"/>
      <xs:enumeration value="National Insurance Number"/>
      <xs:enumeration value="NHS Number"/>
      <xs:enumeration value="Passport Number"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="issuingAuthority">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="institution">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="position">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="title">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="secondaryName">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="subjectArea">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="surname">
    <xs:restriction base="xs:string"/>
  </xs:simpleType>

  <xs:simpleType name="localIdentificationNumber">
    <xs:restriction base="xs:integer"/>
  </xs:simpleType>

  <!-- Complex Type Declarations -->
  <xs:complexType name="academicPost">
    <xs:sequence>
      <xs:element name="currentPost" type="exm:postHeld"/>
      <xs:element name="previousPost" type="exm:postHeld" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="examiner">
    <xs:sequence>
      <xs:element name="personalDetails" type="exm:personalDetails"/>
      <xs:element name="subjectArea" type="xs:string"/>
      <xs:element name="academicPost" type="exm:academicPost"/>
      <xs:element name="PhDDetail" type="exm:PhDDetail"/>
      <xs:element name="previousExperience" type="exm:previousExperience" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="experience">
    <xs:sequence>
      <xs:element name="subjectArea" type="xs:string"/>
      <xs:element name="institution" type="exm:institution"/>
      <xs:element name="examinationDate" type="xs:date"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personName">
    <xs:sequence>
      <xs:element name="title" type="exm:title"/>
      <xs:element name="firstName" type="exm:firstName"/>
      <xs:element name="secondaryName" type="exm:secondaryName" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="surname" type="exm:surname"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personalDetails">
    <xs:sequence>
      <xs:element name="localIdentificationNumber" type="exm:localIdentificationNumber"/>
      <xs:element name="personalIdentification" type="exm:personalIdentification"/>
      <xs:element name="personName" type="exm:personName"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="personalIdentification">
    <xs:sequence>
      <xs:element name="identificationNumber" type="exm:identificationNumber"/>
      <xs:element name="identificationType" type="exm:identificationType"/>
      <xs:element name="issuingAuthority" type="exm:issuingAuthority"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="PhDDetail">
    <xs:sequence>
      <xs:element name="institution" type="exm:institution"/>
      <xs:element name="PhDExaminar" type="exm:personalDetails" maxOccurs="unbounded"/>
      <xs:element name="PhDSupervisor" type="exm:personalDetails" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="postHeld">
    <xs:sequence>
      <xs:element name="position" type="exm:position"/>
      <xs:element name="institution" type="exm:institution"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="previousExperience">
    <xs:sequence>
      <xs:element name="experience" type="exm:experience" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== tuscanmoon/XML-Course-Work-2/examiners.xml
<?xml version="1.0" encoding="UTF-8"?>
<exm:examinerCV xmlns="http://webspace.stu.qmul.ac.uk/~ac08162/amcm043/coursework2/examiner"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:exm="http://webspace.stu.qmul.ac.uk/~ac08162/amcm043/coursework2/examiner"
    xsi:schemaLocation="http://webspace.stu.qmul.ac.uk/~ac08162/amcm043/coursework2/examiner examiners.xsd">
    <exm:examiner>
        <exm:personalDetails>
            <exm:localIdentificationNumber>1</exm:localIdentificationNumber>
            <exm:personalIdentification>
                <exm:identificationNumber>AB123456J</exm:identificationNumber>
                <exm:identificationType>National Insurance Number</exm:identificationType>
                <exm:issuingAuthority>UK Government</exm:issuingAuthority>
            </exm:personalIdentification>
            <exm:personName>
                <exm:title>Dr</exm:title>
                <exm:firstName>Harry</exm:firstName>
                <exm:secondaryName>James</exm:secondaryName>
                <exm:surname>Nesbitt</exm:surname>
            </exm:personName>
        </exm:personalDetails>
        <exm:subjectArea>Inorganic Chemistry</exm:subjectArea>
        <exm:academicPost>
            <exm:currentPost>
                <exm:position>Senior Lecturer</exm:position>
                <exm:institution>The Royal Veterinary College</exm:institution>
            </exm:currentPost>
            <exm:previousPost>
                <exm:position>Lecturer</exm:position>
                <exm:institution>University of Brisol</exm:institution>
            </exm:previousPost>
        </exm:academicPost>
        <exm:PhDDetail>
            <exm:institution>University of Brisol</exm:institution>
            <exm:PhDExaminar>
                <exm:localIdentificationNumber>300</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>GH456234K</exm:identificationNumber>
                    <exm:identificationType>National Insurance Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <exm:title>Dr</exm:title>
                    <exm:firstName>James</exm:firstName>
                    <exm:surname>Bourne</exm:surname>
                </exm:personName>
            </exm:PhDExaminar>
            <exm:PhDExaminar>
                <exm:localIdentificationNumber>310</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>FH455234K</exm:identificationNumber>
                    <exm:identificationType>National Insurance Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <exm:title>Dr</exm:title>
                    <exm:firstName>Jason</exm:firstName>
                    <exm:surname>Bond</exm:surname>
                </exm:personName>
            </exm:PhDExaminar>
            <exm:PhDSupervisor>
                <exm:localIdentificationNumber>320</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>123456789</exm:identificationNumber>
                    <exm:identificationType>Passport Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <title>Miss</title>
                    <firstName>Alicia</firstName>
                    <surname>Keys</surname>
                </exm:personName>
            </exm:PhDSupervisor>
        </exm:PhDDetail>
        <previousExperience>
            <experience>
                <subjectArea>Inorganic Chemistry</subjectArea>
                <institution>University of Bristol</institution>
                <examinationDate>2007-10-02</examinationDate>
            </experience>
            <experience>
                <subjectArea>Inorganic Chemistry</subjectArea>
                <institution>University of Bristol</institution>
                <examinationDate>2007-03-02</examinationDate>
            </experience>
            <experience>
                <subjectArea>Inorganic Chemistry</subjectArea>
                <institution>University of Bath</institution>
                <examinationDate>2006-05-02</examinationDate>
            </experience>
        </previousExperience>
    </exm:examiner>

    <exm:examiner>
        <exm:personalDetails>
            <exm:localIdentificationNumber>2</exm:localIdentificationNumber>
            <exm:personalIdentification>
                <exm:identificationNumber>GH128856J</exm:identificationNumber>
                <exm:identificationType>National Insurance Number</exm:identificationType>
                <exm:issuingAuthority>UK Government</exm:issuingAuthority>
            </exm:personalIdentification>
            <exm:personName>
                <exm:title>Dr</exm:title>
                <exm:firstName>Karen</exm:firstName>
                <exm:secondaryName>Alison</exm:secondaryName>
                <exm:surname>Doyle</exm:surname>
            </exm:personName>
        </exm:personalDetails>
        <exm:subjectArea>Inorganic Chemistry</exm:subjectArea>
        <exm:academicPost>
            <exm:currentPost>
                <exm:position>Senior Lecturer</exm:position>
                <exm:institution>University of Brighton</exm:institution>
            </exm:currentPost>
            <exm:previousPost>
                <exm:position>Lecturer</exm:position>
                <exm:institution>Imperial College</exm:institution>
            </exm:previousPost>
        </exm:academicPost>
        <exm:PhDDetail>
            <exm:institution>Imperial College</exm:institution>
            <exm:PhDExaminar>
                <exm:localIdentificationNumber>200</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>HH467234K</exm:identificationNumber>
                    <exm:identificationType>National Insurance Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <exm:title>Dr</exm:title>
                    <exm:firstName>Andrew</exm:firstName>
                    <exm:surname>Parker</exm:surname>
                </exm:personName>
            </exm:PhDExaminar>
            <exm:PhDExaminar>
                <exm:localIdentificationNumber>210</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>345676543</exm:identificationNumber>
                    <exm:identificationType>Passport Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <exm:title>Dr</exm:title>
                    <exm:firstName>Jason</exm:firstName>
                    <exm:surname>Bond</exm:surname>
                </exm:personName>
            </exm:PhDExaminar>
            <exm:PhDSupervisor>
                <exm:localIdentificationNumber>220</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>123445789</exm:identificationNumber>
                    <exm:identificationType>Passport Number</exm:identificationType>
                    <exm:issuingAuthority>UK Government</exm:issuingAuthority>
                </exm:personalIdentification>
                <exm:personName>
                    <exm:title>Dr</exm:title>
                    <exm:firstName>Gordon</exm:firstName>
                    <exm:surname>Cameron</exm:surname>
                </exm:personName>
            </exm:PhDSupervisor>
        </exm:PhDDetail>
    </exm:examiner>

    <exm:examiner>
        <exm:personalDetails>
            <exm:localIdentificationNumber>3</exm:localIdentificationNumber>
            <exm:personalIdentification>
                <exm:identificationNumber>PW168856H</exm:identificationNumber>
                <exm:identificationType>National Insurance Number</exm:identificationType>
                <exm:issuingAuthority>UK Government</exm:issuingAuthority>
            </exm:personalIdentification>
            <exm:personName>
                <exm:title>Dr</exm:title>
                <exm:firstName>Tony</exm:firstName>
                <exm:secondaryName>Nelson</exm:secondaryName>
                <exm:surname>Mandelson</exm:surname>
            </exm:personName>
        </exm:personalDetails>
        <exm:subjectArea>Organic Chemistry</exm:subjectArea>
        <exm:academicPost>
            <exm:currentPost>
                <exm:position>Senior Lecturer</exm:position>
                <exm:institution>University of Leicester</exm:institution>
            </exm:currentPost>
            <exm:previousPost>
                <exm:position>Lecturer</exm:position>
                <exm:institution>University of Durham</exm:institution>
            </exm:previousPost>
        </exm:academicPost>
        <exm:PhDDetail>
            <exm:institution>Imperial College</exm:institution>
            <exm:PhDExaminar>
                <exm:localIdentificationNumber>100</exm:localIdentificationNumber>
                <exm:personalIdentification>
                    <exm:identificationNumber>HJ465234K</exm:identificationNumber>
